### ISSUE TITLE
[feature request] compile SCSS bytes to CSS bytes

### ISSUE THREAD

**Issue by xyproto** [wellington/sass#42]
Hi,

Thanks for making (the only?) pure Go SCSS to CSS copmpiler. I'm using it in the [Algernon](https://github.com/xyproto/algernon) web server.

It would be great if it was possible to convert from SCSS to CSS given a slice of bytes, without having to give an input filename. Sometimes, converting a single SCSS file that is in a cache, in the form of a byte slice, is desirable.

Something along these lines would be easy to use:

`Compile(scssdata []byte) ([]byte, error) { ... }`

Best regards,
Alexander F Rødseth

**Comment by drewwells** [comment]
I've added the above signature. I noticed tests are failing on Go 1.7 so going to be looking into that. YMMV for now!

**Comment by xyproto** [comment]
Awesome, thanks!
